### ISSUE TITLE
PHP8 support 

### ISSUE THREAD

**Issue by leroy0211** [LoopFiftyFour/PHP-Connector#20]
Please add php `^8.0` support in composer.

**Comment by loop54-christoffer** [comment]
Thank you for opening the issue! We're looking into it.

**Comment by alecritson** [comment]
PHP8 is still failing since `ramsey/uuid` is locked to `^3.8`, which only supports `^5.4 || ^7.0`.

https://packagist.org/packages/ramsey/uuid#3.8.0

Ideally, it'd be good to get it on to v4 to support frameworks such as Laravel.

**Comment by joelwkall** [comment]
Thanks, we're looking into it!

**Comment by oleg-loop54** [comment]
PHP 8.* is now supported!
