### ISSUE TITLE
Can't install module with ramsey/uuid ^4. 

### ISSUE THREAD

**Issue by alexandrosk** [LoopFiftyFour/PHP-Connector#23]
Hello!
should "ramsey/uuid": "^3.8" be required like this? I guess version 4 should also be fine! 
Can we make a branch and change this to ^4?

**Comment by alexandrosk** [comment]
If you give me access to push a branch I can add a PR :)

**Comment by loop54-christoffer** [comment]
Hello @alexandrosk ! Thank you so much for your input. Are you not able to fork the repository and create a PR that way?

**Comment by alexandrosk** [comment]
@loop54-christoffer That's correct Christoffer, I will create a PR for this, 
I want to include the package on a magento2 environment (2.4.3 version) which has some different requirements than the module but I don't believe we will have any issues, I will fix the dependancies test and create a PR for a new branch maybe.

Because without these changes anyone trying to include the package to a magento repo won't be able to do it
Thanks!

**Comment by oleg-loop54** [comment]
This is fixed with `"ramsey/uuid": "^3.8|^4.0"`
