### ISSUE TITLE
Wrong method calling

### ISSUE THREAD

**Issue by alexander-binas** [LoopFiftyFour/PHP-Connector#3]
If your class using in the code with some namespaces following code can works wrong:
setCookie('Loop54User', $userId, time() + (86400 * 365), "/");

The best way is to use 'self':
self::setCookie('Loop54User', $userId, time() + (86400 * 365), "/");

**Comment by joelwkall** [comment]
Thanks! We'll fix that!

**Comment by joelwkall** [comment]
No longer relevant with V3 library
