### ISSUE TITLE
Wrong argument order for Client::getPopularEntities()

### ISSUE THREAD

**Issue by rmilesson** [LoopFiftyFour/PHP-Connector#32]
Hi!

I just noticed that the argument order for `Client::getPopularEntities( $behaviorType, $forUserId, $entityType )` differs from `GetPopularEntitiesRequest($behaviorType, $entityType, $forUserId)`.

`Client.php`
```php
public function getPopularEntities($behaviorType, $forUserId = null, $entityType = null)
{
    return new GetPopularEntitiesRequest($behaviorType, $forUserId, $entityType);
}
```

`GetPopularEntitiesRequest.php`
```php
public function __construct($behaviorType, $entityType, $forUserId)
{
    $this->wraps(new OpenAPI\Model\GetRecentEntitiesRequest([
        'behavior_type' => $behaviorType,
        'entity_type' => $entityType,
        'for_user_id' => $forUserId,
    ]));
}
```

**Comment by Rayn93** [comment]
Hi @rmilesson 
Thank you for notice this problem. It is already fixed: https://github.com/LoopFiftyFour/PHP-Connector/pull/35
