### ISSUE TITLE
Trying to modify headers in /vendor/loop54/php-connector/lib/RemoteClientInfo/WebClient.php on line 31

### ISSUE THREAD

**Issue by rmilesson** [LoopFiftyFour/PHP-Connector#33]
Hi!

The WebClient is trying to set the user ID cookie in `/vendor/loop54/php-connector/lib/RemoteClientInfo/WebClient.php` on line 31. This is undesired since headers might already be sent.

**Comment by Rayn93** [comment]
Hi @rmilesson 
Please try to set:

`output_buffering = On`

in your php.ini file. 

It should fix waring about headers already be sent.

**Comment by rmilesson** [comment]
@Rayn93 

It fixes nothing. It just hides the underlying issue. I cannot be expected to change how we serve our application just to make what is basically an API-call to get a list of products.

**Comment by Rayn93** [comment]
@rmilesson 
Yes, you are right. It is just a hot fix for your issue.
When the main programmer of this library returns, he should rebuild the logic so that the warning does not appear.

**Comment by oleg-loop54** [comment]
Hi @rmilesson this is fixed in #36. There is a breaking change, so we've bumped major version number to 3.x.x
