### ISSUE TITLE
Remove UTF-8 BOM from Loop54-Minified.php

### ISSUE THREAD

**Issue by DyaGa** [LoopFiftyFour/PHP-Connector#5]
It throws warnings:

```
Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/vendor/loop54/php-connector/dist/Loop54-Minified.php:1)
```

**Comment by joelwkall** [comment]
Thank you for opening this issue. We are aware of this problem. We will release a new version of the connector soon that addresses this problem. 

As a workaround, you can open Loop54-Minified.php in a text editor and convert it to UTF8 without BOM or any other encoding that corresponds to the encoding that you use for your other PHP files.

**Comment by joelwkall** [comment]
Hi and sorry for the late reply. We are discussing whether to fix it now or to wait for the new version. In the meantime, you can use the workaround I mentioned - unless that did not work for you?

**Comment by DyaGa** [comment]
We use another workaround. We just copied `Loop54-Minified.php` without BOM into the project.

**Comment by kqr** [comment]
This is fixed in 029c86 (which, again, was committed a while ago.) Thank you for your issue reports!
