### ISSUE TITLE
Return `null` in `getIP` method if filter is fails

### ISSUE THREAD

**Issue by DyaGa** [LoopFiftyFour/PHP-Connector#6]
In some cases method `Utils::getIP` can return `false` (see [Utils#L85](https://github.com/LoopFiftyFour/PHP-Connector/blob/master/Utils.php#L85) and [filter_var documentation](https://secure.php.net/manual/en/function.filter-var.php)). And this makes `Utils::escape` method to trigger a notice message "Argument val must be string." while serializing request in [Request#L59](https://github.com/LoopFiftyFour/PHP-Connector/blob/master/Request.php#L59).

I think the method should return `null` when `filter_var` returns `false`.

**Comment by joelwkall** [comment]
Good catch. We will take this into account when building our new version. Thank you!

**Comment by kqr** [comment]
This is fixed by ab1ad48. (Which was committed a while ago, and only just now did I notice this issue. Sorry!)
